import '../chat_screen/widgets/chat_item_widget.dart';import 'package:flutter/material.dart';import 'package:homecampus/core/app_export.dart';import 'package:homecampus/presentation/chat_delete_page/chat_delete_page.dart';import 'package:homecampus/presentation/notification_page/notification_page.dart';import 'package:homecampus/presentation/saved_page/saved_page.dart';import 'package:homecampus/presentation/scheduled_status_page/scheduled_status_page.dart';import 'package:homecampus/widgets/app_bar/appbar_image.dart';import 'package:homecampus/widgets/app_bar/appbar_subtitle_5.dart';import 'package:homecampus/widgets/app_bar/custom_app_bar.dart';import 'package:homecampus/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class ChatScreen extends StatelessWidget {GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(82), centerTitle: true, title: Container(height: getVerticalSize(44), width: getHorizontalSize(338), child: Stack(children: [AppbarImage(height: getVerticalSize(44), width: getHorizontalSize(338), svgPath: ImageConstant.imgShape), Padding(padding: getPadding(left: 23, top: 15, right: 196, bottom: 13), child: Row(children: [AppbarImage(height: getSize(11), width: getSize(11), svgPath: ImageConstant.imgSearch, margin: getMargin(bottom: 3)), AppbarSubtitle5(text: "Search Message", margin: getMargin(left: 10))]))])), actions: [Padding(padding: getPadding(left: 58, right: 10), child: SizedBox(height: getVerticalSize(46), child: VerticalDivider(width: getHorizontalSize(1), thickness: getVerticalSize(1), color: ColorConstant.whiteA7006c, indent: getHorizontalSize(10)))), AppbarImage(height: getVerticalSize(20), width: getHorizontalSize(23), svgPath: ImageConstant.imgMicrophone, margin: getMargin(left: 17, top: 18, right: 68, bottom: 8))]), body: Padding(padding: getPadding(left: 36, top: 34, right: 35), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: getVerticalSize(24));}, itemCount: 5, itemBuilder: (context, index) {return ChatItemWidget(onTapChatsection: () {onTapChatsection(context);});})), bottomNavigationBar: CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}))); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.scheduledStatusPage; case BottomBarEnum.Explore: return "/"; case BottomBarEnum.Chat: return AppRoutes.chatDeletePage; case BottomBarEnum.Saved: return AppRoutes.savedPage; case BottomBarEnum.Profile: return AppRoutes.notificationPage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.scheduledStatusPage: return ScheduledStatusPage(); case AppRoutes.chatDeletePage: return ChatDeletePage(); case AppRoutes.savedPage: return SavedPage(); case AppRoutes.notificationPage: return NotificationPage(); default: return DefaultWidget();} } 
onTapChatsection(BuildContext context) { Navigator.pushNamed(context, AppRoutes.chatRoomScreen); } 
 }
