import 'package:flutter/material.dart';import 'package:homecampus/core/app_export.dart';import 'package:homecampus/widgets/custom_button.dart';import 'package:homecampus/widgets/custom_icon_button.dart';import 'package:homecampus/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class StudentForgotPasswordScreen extends StatelessWidget {TextEditingController emailoneController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.gray90005, resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: getPadding(left: 38, top: 35, right: 38, bottom: 35), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.centerLeft, child: Container(height: getVerticalSize(382), width: getHorizontalSize(300), child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.bottomRight, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgImage228x195, height: getVerticalSize(228), width: getHorizontalSize(195), alignment: Alignment.center), Padding(padding: getPadding(top: 49), child: Text("Forgot Password?", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPoppinsBold22)), Container(width: getHorizontalSize(263), margin: getMargin(top: 12), child: Text("Enter your email address for the verification process, we will send code to your email", maxLines: null, textAlign: TextAlign.left, style: AppStyle.txtPoppinsRegular12WhiteA700))])), CustomIconButton(height: 37, width: 37, alignment: Alignment.topLeft, onTap: () {onTapBtnIcback(context);}, child: CustomImageView(svgPath: ImageConstant.imgIcback))]))), Padding(padding: getPadding(left: 36, top: 50, right: 39), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("Email", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtPlusJakartaSansRomanSemiBold14), CustomTextFormField(focusNode: FocusNode(), autofocus: true, controller: emailoneController, hintText: "1234mail@gmail.com", margin: getMargin(top: 9), variant: TextFormFieldVariant.OutlineIndigoA100, padding: TextFormFieldPadding.PaddingT14, fontStyle: TextFormFieldFontStyle.PlusJakartaSansItalicMedium16, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress)])), CustomButton(text: "Recover Password", margin: getMargin(left: 37, top: 29, right: 38, bottom: 5), variant: ButtonVariant.GradientRed900Deeporange600, fontStyle: ButtonFontStyle.PlusJakartaSansRomanSemiBold16, onTap: () {onTapRecover(context);})]))))); } 
onTapBtnIcback(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginStudentScreen); } 
onTapRecover(BuildContext context) { Navigator.pushNamed(context, AppRoutes.studentEmailOtpCodeScreen); } 
 }
